version: "3.9"

services:
    php-fpm:
        container_name: php-fpm
        build: ./php-fpm/
        volumes:
            - ./www:/var/www
    nginx:
        container_name: nginx
        build: ./nginx/
        volumes:
            - ./php/www:/usr/share/nginx/html
        ports:
          - "80:80"
        depends_on:
          - "php-fpm"
